parameters: 
  connected_service_name_arm: ''
  
steps:
  - task: AzurePowerShell@4
    displayName: "Run Configuration Script"
    inputs:
      azurePowerShellVersion: latestVersion
      azureSubscription: ${{ parameters.connected_service_name_arm }}
      scriptType: 'FilePath'
      scriptPath: '$(Pipeline.Workspace)/importsettings/import-settings.ps1'
      scriptArguments:
        -app_config_name $(app_config_name) `
        -path $(Pipeline.Workspace)/settings/ `
        -environment $(environment) `
        -useenv $true
      errorActionPreference: 'continue'
    env:
      ARM_CLIENT_ID: $(ARM_CLIENT_ID)
      ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
      ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
      ARM_TENANT_ID: $(ARM_TENANT_ID)
